-- Cria a tabela de itens
create table user_items (
  id bigint generated by default as identity primary key,
  user_id text not null, -- ID de usuário
  text text not null,    -- O termo do autocomplete
  frequency int not null, -- 'f' frequência de uso
  updated_at bigint not null, -- 'up' timestamp da última atualização
  
  unique(user_id, text) -- Um usuário não pode ter o mesmo termo duplicado
);

-- Cria um índice para a busca ficar rápida
create index idx_user_items_search on user_items(user_id, text);

------------------------

-- Função para sincronizar dados do usuário
create or replace function sync_user_data(
  p_user_id text,
  p_changes jsonb
) returns void as $$
begin
  -- Insere ou Atualiza (Upsert) em lote
  insert into user_items (user_id, text, frequency, updated_at)
  select 
    p_user_id,
    (item->>'text'),
    (item->>'frequency')::int,
    (item->>'updated_at')::bigint
  from jsonb_array_elements(p_changes) as item
  on conflict (user_id, text) 
  do update set 
    frequency = excluded.frequency,
    updated_at = excluded.updated_at
  where excluded.updated_at > user_items.updated_at;
  -- A linha acima garante que só atualiza se o dado novo for mais recente
end;
$$ language plpgsql; -- Fim da função sync_user_data

---------------------------------

-- 1. Permitir LEITURA (Select) para que o Full Download e Deltas funcionem
create policy "Permitir Leitura Publica"
on user_items for select
using ( true );

-- 2. Permitir INSERÇÃO (Insert) para novos dados
create policy "Permitir Inserção Publica"
on user_items for insert
with check ( true );

-- 3. Permitir ATUALIZAÇÃO (Update) para quando a frequência muda
create policy "Permitir Atualização Publica"
on user_items for update
using ( true );